<?php

/**
 * @file
 * Contains custom_solr_search.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_solr_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_solr_search module.
    case 'help.page.custom_solr_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Solr Search') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_solr_search_theme($existing, $type, $theme, $path) {
  return array(
    'custom_solr_search_result' => array(
      'variables' => array(
        'url' => NULL,
        'title' => NULL,
        'author' => NULL,
        'publishDate' => NULL,
        'publisher' => NULL,
        'topic' => NULL
      ),
      'path' => $path . '/templates',
      'template' => 'custom-solr-search-result',
    ),
  );
}